import type { Metadata } from "next";
import "@/styles/globals.scss";
import styles from "./layout.module.scss";
import Header from "@/components/main/Header/Header";
import Footer from "@/components/main/Footer/Footer";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Main",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />

          <nav className={styles.main_body}>
            <main className={styles.main_content_block}>{children}</main>
          </nav>

          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
