import type { Metadata } from "next";
import "@/styles/globals.scss";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import styles from "./layout.module.scss";
import MainHeader from "@/components/main/Header/ui/main/MainHeader/MainHeader";
import Footer from "@/components/main/Footer/Footer";

export const metadata: Metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <MainHeader />
          <div className={styles.main_body}>{children}</div>
        </NextIntlClientProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
